### PR TITLE
Adding box model to teacup

### PR DESCRIPTION
**Pull request by boberetezeke**
This pull request is really for your review only. There some debug functions I threw in that I would like to see maybe integrated into BubbleWrap. Aside from that. You can see how it is used in boberetezeke/task-it-ios project in tasks_controller.rb. 

Also the box model flow engine needs more work. If you have a row of items and you have a vertically stretchable item in that view, then it won't work correctly. I would also like to make margins stretchable as well (for centering for example). 

Lastly I really don't know how this would integrate with auto-layout. Your feedback would be GREATLY appreciated!

### CODE REVIEW

**Comment by colinta** [comment]
This is very cool!  I don't feel very good about polluting the UIView class to _this_ extent, at least not in a tool that is supposed to be as generic as teacup (I already don't like that we have to pollute `UIView` and `UIViewController` _at all_, but that was unavoidable if this thing was gonna be at all useful).

Seems like this would still be useful as a separate gem - what are your thoughts there?

**Comment by boberetezeke** [comment]
Before I reply, I have to look at your changes involving auto-layout in 
iOS 6.

"You must be the change you want to see in the world." Mahatma Gandhi

blog: http://steve.stewdle.com/blog
twitter: @boberetezeke

**Comment by colinta** [comment]
Also, UICollectionView will largely remove the need for a box model (and make my own `TypewriterView` obsolete!)

**Comment by colinta** [comment]
@boberetezeke lemme know if you still feel a need for a box model, I've been happy with constraints (though they are NOT NEARLY as straightforward - but very powerful!).  I'm closing in the meantime.  Thanks again for playing with the core code!  I hope it made sense! :smile:

**Comment by boberetezeke** [comment]
I haven't gotten back to this to break it out of teacup anyway. I will 
have to do that and/or learn constraints.

Thanks for working with me on it.

Steve

"You must be the change you want to see in the world." Mahatma Gandhi

blog: http://steve.stewdle.com/blog
twitter: @boberetezeke

**Pull request closed without merging**
