### PR TITLE
Separated layout behavior from style behavior

### PR DESCRIPTION
**Pull request by farcaller**

### CODE REVIEW

**Comment by colinta** [comment]
`layout_left` and `layout_right` sound very much like "floating"... (hold on, i'm gonna type up some things to compare)

**Comment by farcaller** [comment]
offset is based on four values, let's not "over-cssify" it, it's better with keywords.

On the difference between the layout and style. Layout is more like positioning the view (frame and bounds), style is more like UIAppearance.

**Comment by colinta** [comment]
> let's not "over-cssify" it

I agree!  But we disagree on which is more CSS-like, apparently... :-/

Right now, using straight up rubymotion, we set the frame like so:

``` ruby
self.view.frame = [[10, 10], [310, 450]]
```

behind the scenes, this becomes a `CGRect`:

```
r = CGRectMake()
r.size  # CGSize
r.size.width
r.size.height

r.origin # CGPoint
r.origin.x
r.origin.y
```

To me, this becomes:

``` ruby
frame = [[10, 10], [310, 450]]
# or:
position = [10, 10]
size = [310, 450]
# or even:
x = 10
y = 10
width = 310
height = 450
```

Bridging the two formats (teacup, and cocoa) makes it that much easier to learn and start using

**Comment by farcaller** [comment]
it's just that offset could be like

``` ruby
offset = { left: 7, right: -3 }
```

so we cannot speak about the frame at this point. It is calculated later on, based on the offsets, fixed sizes, etc.

**Comment by colinta** [comment]
AH, good point.  So this is relative positioning, rather than absolute.

**Comment by colinta** [comment]
Well, anyway, this is a great proposal - merging it in!

**Comment by farcaller** [comment]
Yup, the whole point of it is about relative positioning :)

**Pull request merged**
