### PR TITLE
Separated layout & stylesheet proposals

### PR DESCRIPTION
**Pull request by farcaller**
We are looking for different options not only for managing UI theming but also for generic UI management and controls placement.

### CODE REVIEW

**Comment by beakr** [comment]
I think this is a nice idea, will lead us to nicer, categorized proposal management.

**Comment by beakr** [comment]
How about we place two folders - `styles/`, and `layout/`, in one proposals folder. I'll happily merge it then.

**Comment by farcaller** [comment]
Done.

**Comment by beakr** [comment]
Thanks.

**Pull request merged**
