### PR TITLE
tossing in twitter bootstrap as method to bind view to styles

### PR DESCRIPTION
**Pull request by smtm**
I kinda like twitter bootstrap, as it lets me focus on creating a page and not on CSS tweaks.
They do a good job with their naming convention and so on. So that would be a great way, and tons of people know bootstrap...

### CODE REVIEW

**Comment by beakr** [comment]
So, by this you're talking about default classes for bootstrapping teacup styles?

**Comment by smtm** [comment]
Yeah they have some very good defaults, and you build on top of that or override and extend the styles.
You end up with HTML that you can give to a CSS / Designer guy and they instantly know how stuff plays together and don't have to go on a CSS style exploration trip..

Cuts down the time to get to the meat of a project

**Comment by beakr** [comment]
We may start off with just plain styles, and leave it to other users to extend their own bootstrapping frameworks.

**Comment by colinta** [comment]
The wording here sounds like it is actually referring to HTML, not to Cocoa / iOS.

And beakr's point is a good one - we're not going to be offering much if anything in the way of 'new' styles.  The point is more to get solutions for building and modifying the view hierarchy.

**Comment by beakr** [comment]
Exactly, we'll lead it to others (or ourselves) to make external libraries, just as RubyMotion has done for us.

**Comment by beakr** [comment]
Note that we wouldn't mind if you stuck along with the project, and when it's release comes, make your own teacup-bootstrap. It's just that the default libraries will only contain the raw basics of layout, and stylesheet code.

**Comment by smtm** [comment]
No worries, thanks for showing what is in scope and what is not..

It was just a thought I wanted to share as using twitter bootstrapped usage this has really eased the workflow for me in the area of html/css templates (I mostly do rails) and got me to think more in terms of user interface and interaction. The clever thing about it is that the CSS class names are easy to remember: You start slowly integrating some UI elements and the knowledge expands gradually as one uses it.

This is a newbie experience people will be looking for...

**Pull request closed without merging**
