### PR TITLE
This one's for reals.

### PR DESCRIPTION
**Pull request by colinta**
This is it guys, this is the fruit of my toils.

fixes everything I can think of (#30, #41: orientation styles, extendid styles, class styles, and imported styles - SEESH) and adds everything from my proposal #40.  And of course it's a gem (#38).

### CODE REVIEW

**Comment by ConradIrwin** [comment]
This stuff looks awesome, thanks!

**Comment by colinta** [comment]
This morning I tried it on the app I'm working on, except I had added an exception for empty `style` declarations

```
style :name_only => raise
```

I'm gonna push a quick patch that allows these to remain (they were allowed in v0.2)

**Comment by colinta** [comment]
k, that is ready (v0.3.1).  @ConradIrwin - https://rubygems.org/gems/teacup, gem build / gem push, please! :-)

**Comment by colinta** [comment]
As I'm writing the announcement, I realized that `UIView.teacup_handler` is limited to only work on `UIView` classes... you can't, for instance, write a handler for `CGLayer.teacup_handler :shadow`.

should we change this to:

``` ruby
Teacup.handler UIButton, :title do ... end
```

or add teacup_handler to `NSObject`, and keep the current syntax?

**Comment by colinta** [comment]
I'm going with `Teacup.handler klass, stylename`.  I don't think this feature is worth mucking around in UIKit classes for, and this syntax is certainly palatable.

**Pull request merged**
